---
- hosts: all
  tasks:
  
    - name: add ivoz apt repository
      apt_repository: 
        repo: 'deb http://packages.irontec.com/debian artemis main extra' 
        state: present 
        filename: ivozprovider.list 
        update_cache: yes
    - name: add klear apt repository
      apt_repository: 
        repo: 'deb http://packages.irontec.com/debian tayler main' 
        state: present 
        filename: klear.list
        update_cache: yes
          
          
