---
- hosts: all
  roles:
    - role: pkorobeinikov.apt-repository
      apt_repository_repositories:
        - repo: deb http://packages.irontec.com/debian artemis main extra
        - repo: deb http://packages.irontec.com/debian tayler main
          
