---
- hosts: all
# Add specified repository into sources list using specified filename.
- name: add ivoz apt-key
  apt_key: 
    url: http://packages.irontec.com/public.key 
    state: present 

- name: add ivoz apt repository
  apt_repository: 
    repo: 'deb http://packages.irontec.com/debian artemis main extra' 
    state: present 
    filename: ivozprovider.list 
    update_cache: yes
- name: add klear apt repository
  apt_repository: 
    repo: 'deb http://packages.irontec.com/debian tayler main' 
    state: present 
    filename: klear.list
    update_cache: yes

          
          
